- name: Deploy DevStack on Ubuntu
  hosts: all
  become: true
  become_method: sudo
  gather_facts: true

  vars:
    user: stack
    global_env: {}
    devstack_workdir: /home/{{ user }}/devstack

  roles:
    - role: install-golang
    - role: install-devstack
    - role: install-docker